Initial WIP
edgefarm/nats-leafnode pull request #1
Opened 2021-06-08 19:28 UTC by KlausPopp

2021-06-10 13:25 UTC, siredmar requested changes

2021-06-10 13:25 UTC, siredmar commented on nats-config-provider/main.go
> +		if creds != "" && creds != oldCreds {
if err != nil && crets != oldCreds

2021-06-10 14:08 UTC, KlausPopp commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
Why? It nats-config-provider is only a part of the container. For me, it is more logical that it stays in root. Otherwise, I would have to move also the config files, which are not related to nats-config-provider

2021-06-10 14:08 UTC, KlausPopp commented on Dockerfile
> +COPY ./nats-config-provider /go/src/nats-config-provider
See above. I won't do that

2021-06-10 14:19 UTC, KlausPopp commented on nats-config-provider/main.go
> +	_, err = f.WriteString(creds)
No. It's correct. If WriteString returns an error, it is passed via return

2021-06-10 14:24 UTC, KlausPopp commented on README.md
> +The docker image built from that repo contains a NATS server configured as a NATS leaf node, the leaf node connects to a NATS Server in the cloud (NGS operated by Synadia).
Ok

2021-06-10 14:24 UTC, KlausPopp commented on README.md
> +The docker image built from that repo contains a NATS server configured as a NATS leaf node, the leaf node connects to a NATS Server in the cloud (NGS operated by Synadia).
Ok

2021-06-10 14:25 UTC, KlausPopp commented on README.md
> +To be able to connect to NGS, the leaf node server needs user credentials. This container provides user credentials to the leaf node server through the MS IoTHub module twin.
Ok

2021-06-10 14:26 UTC, KlausPopp commented on README.md
> +Therefore, the nats-config-provider process reads periodically the Module Twin. If it detects a change in the `desired.nats.leafnode-creds` field, it writes the credentials to `/nats-leaf.creds` and
Ok

2021-06-10 14:27 UTC, KlausPopp commented on README.md
> +Note: The whole credentials file must be in a single json line. The lines within the string have to be separated by `\n`
Ok

2021-06-10 18:40 UTC, KlausPopp commented on README.md
> +The `pipeline.yaml` is the CI/CD pipeline that builds all the alm service module docker images for different architectures. The images are published on [docker hub](https://hub.docker.com/u/ci4rail)
Thanks. There is another error. The pipeline only pushes to harbor, not docker hub. Do we need both?

2021-06-10 18:41 UTC, KlausPopp commented on README.md
> +
Ok

2021-06-10 18:43 UTC, KlausPopp commented on README.md
> +Copy `ci/credentials-pullrequests.template.yaml` to `ci/credentials-pullrequests.yaml` and copy  the content from `alm-service-modules credentials-pullrequests.yaml` found in bitwarden.
Ok

2021-06-10 18:44 UTC, KlausPopp commented on README.md
> +Copy `ci/credentials-pullrequests.template.yaml` to `ci/credentials-pullrequests.yaml` and copy  the content from `alm-service-modules credentials-pullrequests.yaml` found in bitwarden.
Sorry for the bad quality of the README.

2021-06-10 18:46 UTC, KlausPopp commented on dobi.sh
> +    dobi --filename meta.yaml list
OK

2021-06-10 18:46 UTC, KlausPopp commented on dobi.sh
> +exec dobi --filename meta.yaml ${@}
Ok

2021-06-10 18:47 UTC, KlausPopp commented on meta.yaml
> +  project: ads-service-modules
Ok

2021-06-10 18:48 UTC, KlausPopp commented on version.yaml
> +  tags: ["0.6.2"]
Ok

2021-06-10 18:48 UTC, KlausPopp commented on pipeline.yaml
> +          dockerfile: source/Dockerfile
See above. No change

2021-06-10 18:49 UTC, KlausPopp commented on pipeline.yaml
> +          build: source/
See above. No change

2021-06-10 19:00 UTC, KlausPopp commented on nats-config-provider/main.go
> +	for i := 0; i < timeoutSeconds; i++ {
This is not the same. I want to sleep for 1 second and then retry. In your code, we would retry forever,
I see don't see a need for a change.
BTW: This is the code from ads-node module:
```
     go func() {
		c, err := iotdevice.NewModuleFromEnvironment(iotmqtt.NewModuleTransport(), true)
		if err != nil {
			log.Fatal(err)
		}
		for i := 0; i < connectTimeoutSeconds; i++ {
			if err = c.Connect(context.Background()); err != nil {
				log.Printf("Connect failed: %s\n", err)
				log.Println("Reconnecting to 'edgeHub'")
			} else {
				log.Println("Connected to 'edgeHub'")
				iothubChan <- c
				return
			}
			time.Sleep(time.Second)
		}
	}()
```

2021-06-10 19:04 UTC, KlausPopp commented on nats-config-provider/main.go
> +func getLeafeNodeCredsFromModuleTwin(c *iotdevice.ModuleClient) string {
Ok

2021-06-10 19:04 UTC, KlausPopp commented on nats-config-provider/main.go
> +			return creds.(string)
Ok

2021-06-10 19:04 UTC, KlausPopp commented on nats-config-provider/main.go
> +		if creds != "" && creds != oldCreds {
Ok

2021-06-11 06:11 UTC, siredmar commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
Ich verstehe Ihre Sichtweise. Aber was mich konkret daran stört, ist, dass eine supervisord.conf- und eine nats-server.config-Datei ohne jeden Kontext herumliegen.
Btw, alle unsere anderen Repos haben ihre Docker-Dateien im Rahmen ihrer Dienste. Das würde ich auch hier gerne sehen.
Aber warum? Es gibt einen Grund dafür, die Docker-Datei in die Nähe der Quellen zu legen und nicht in das Stammverzeichnis eines Repos. Der Grund ist der Kontext. Sicher, im Moment existiert das Repository nur für einen kleinen Dienst. Aber trotzdem ist meiner Meinung nach der richtige Ort, sie in der Nähe des Quellcodes zu platzieren. Auch die Konfiguration der Dockerdatei (nats-server.conf und supervisord.conf) gehört in die Nähe der Dockerdatei. Mein Vorschlag lautet also wie folgt:
```
nats-konfig-provider/Dockerfile
nats-config-provider/config/nats-server.config
nats-config-provider/config/supervisord.conf
```

2021-06-11 06:34 UTC, siredmar commented on nats-config-provider/main.go
> +	for i := 0; i < timeoutSeconds; i++ {
Ok, then i misunderstood what you are trying to do.

2021-06-11 06:34 UTC, siredmar commented on nats-config-provider/main.go
> +	_, err = f.WriteString(creds)
ok

2021-06-11 06:34 UTC, siredmar commented on pipeline-pullrequests.yaml
> +            status: failure
alright then

2021-06-11 06:34 UTC, siredmar commented on pipeline.yaml
> +                cat gitversion/json/gitversion.json
alright then.

2021-06-11 07:46 UTC, siredmar commented on Dockerfile
> +CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
I'd be also fine if the three files where moved to `docker/`
```
docker/Dockerfile
docker/config/nats-server.config
docker/config/supervisord.conf
```

2021-06-14 14:14 UTC, siredmar requested changes

2021-06-15 08:18 UTC, KlausPopp commented on docker/Dockerfile
> +# DEBUG AIDS
Ok. Done

2021-06-15 08:18 UTC, merged